baseURL: "https://blog.mikael.green/"
languageCode: "en-us"
title: "Mikael Grön"

defaultContentLanguage: "en"
style: default
disqusShortname: "blog-mikael-green"
googleAnalytics: "G-HBMN46W2FK"

params:
  description:
  disabled_logo: true
  logo_text: "Blogs about anything"
  date_format: "Jan 2, 2006"

module:
  imports:
    - path: github.com/Mitrichius/hugo-theme-anubis
      disable: false
      theme: "hugo-theme-anubis"
